### ISSUE TITLE
Incompatibility / Core Issue. Entity, Particles, Block breaking textures, Dropped items rendering issues.

### ISSUE THREAD

**Issue by iceeburr** [DerpDerpling/Fadeless#3]
After careful debugging I came to the point that this mod causes the game to break. I broke down my mod configuration into different folders each containing mods of the same kind (example: optimization, rendering, utility, UI, clients, etc.). After finding the problematic folder I broke it down into chunks of mods, once I found the chunk I tested each mod from it individually and I guess fadeless causes this issue. I can't really explain it with words so just watch the video below. From what I experience I see it breaks most entities, their rendering, the player model, block rendering, particles, block breaking animations, etc. A funny thing is that with the Physics mod if you enable cloth simulation you will have a floating cape with no player character.

https://github.com/DerpDerpling/Fadeless/assets/85520957/bc05e11f-fabf-467e-a08d-cbef0d44756a

Here is my full configuration of mods that I encountered this bug on:
https://cdn.discordapp.com/attachments/1098619900773277729/1155483922386407424/j8zcSL4LVw3ibqehdA.mp4

I hope it gets fixed sooner.

**Comment by DerpDerpling** [comment]
I will look into this. Does the issue normally occur after reloading resources?

**Comment by DerpDerpling** [comment]
id recommend trying out the latest version of the mod, i recently made a change that fixed an issue with SkinShuffle, and maybe it fixes your issue too?

**Comment by iceeburr** [comment]
It's been a while since I opened this issue. I don't think it is relevant anymore so I will close it.
