### ISSUE TITLE
Remove subtitle animation

### ISSUE THREAD

**Issue by zajdov** [DerpDerpling/Fadeless#8]
Since this mod is about removing all fade out animations, I thought it would be cool if it also removed the subtitle animation of slowly turning darker when a sound stops.

**Comment by DerpDerpling** [comment]
https://github.com/user-attachments/assets/25d6f7e2-aeba-4b20-990c-08a9f1720ce2

managed to get it working

**Comment by zajdov** [comment]
> managed to get it working

You're the greatest. I hope it didn't bloat your minimal size mod jar too much 😅

**Comment by DerpDerpling** [comment]
currently working a bit of a bigger(ish) update for the mod that removes a couple of other fade out animations and adds a config.

**Comment by DerpDerpling** [comment]
its been added in release 2.0.0, you can get it here or on modrinth/curseforge: https://github.com/DerpDerpling/Fadeless/releases/tag/2.0.0
